stages:
  - prepare
  - linters
  - test
  - swagger
  - deploy
  - release

.cache-tpl: &cache-tpl
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules
    - frontend/components
  policy: pull-push

.test-template: &test-template
  image: node:10-stretch
  stage: test
  tags:
    - docker
  cache:
    <<: *cache-tpl
  variables:
      TZ: "America/New_York"
  before_script:
    - 'echo "INFO: NB node packages : $(ls node_modules | wc -l)"'
    - 'echo "INFO: NB bower packages : $(ls frontend/components | wc -l)"'
  except:
    variables:
      - $SKIP_TESTS
    refs:
      - tags@linagora/lgs/openpaas/linagora.esn.calendar


prepare:
  image: node:10-stretch
  stage: prepare
  tags:
    - docker
  cache:
    <<: *cache-tpl
    policy: pull
  script:
    - npm install
    # Weird behaviour: at the time, npm postinstall was not called.
    - ./node_modules/.bin/bower install --allow-root
    - 'echo "INFO: NB node packages : $(ls node_modules | wc -l)"'
    - 'echo "INFO: NB bower packages : $(ls frontend/components | wc -l)"'
  except:
    variables:
      - $SKIP_PREPARE

linters:
  <<: *test-template
  stage: linters
  script:
    - ./node_modules/.bin/grunt -v linters
  except:
    variables:
      - $SKIP_LINTERS
    refs:
      - tags@linagora/lgs/openpaas/linagora.esn.calendar

check_author:
  image: docker-registry.linagora.com:5000/lgs-releases/gitlab-integrity-checks:latest
  stage: linters
  variables:
    GIT_DEPTH: "1"
  tags:
    - docker-medium
    - check-author
  script:
    - check_author.py check "$GITLAB_USER_EMAIL" "$GITLAB_USER_NAME" --no-accents
  except:
    refs:
      - master@linagora/lgs/openpaas/linagora.esn.calendar
      - tags@linagora/lgs/openpaas/linagora.esn.calendar
      - /^release-.*/@linagora/lgs/openpaas/linagora.esn.calendar

####### tests without services requirements
test_frontend:
  <<: *test-template
  image: docker-registry.linagora.com:5000/public-releases/openpaas-esn-test-helper:1.1.0
  script:
    - ./node_modules/.bin/grunt -v test-frontend

test_unit_backtend:
  <<: *test-template
  script:
    - ./node_modules/.bin/grunt -v --chunk=1 test-unit-backend

####### tests with services requirements

test_midway_backtend:
  <<: *test-template
  services:
    - name: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
      alias: elasticsearch
      command: [ "bin/elasticsearch", "-Ediscovery.type=single-node" ]
    - name: mongo:3.2.0
      alias: mongo
    - name: redis:latest
      alias: redis
    - name: rabbitmq:3.6.5-management
      alias: rabbitmq
  variables:
    MONGO_HOST: mongo
    MONGO_PORT: 27017
    AMQP_HOST: rabbitmq
    AMQP_PORT: 5672
    ELASTICSEARCH_HOST : elasticsearch
    ELASTICSEARCH_PORT: 9200
    REDIS_HOST: redis
    REDIS_PORT: 6379
  script:
    - TZ="Europe/Paris" ./node_modules/.bin/grunt -v --chunk=1 test-midway-backend

swagger:
  <<: *test-template
  stage: swagger
  script:
    - ./node_modules/.bin/grunt swagger-generate
    - ./node_modules/.bin/grunt swagger-validate
  artifacts:
    paths:
      - ./doc/swagger/calendar-swagger.json

deploy-swagger:
  stage: deploy
  tags:
    - deployment
    - api.open-paas.org
    - shell
  environment:
    name: api
    url: https://api.open-paas.org
  only:
    - master@linagora/lgs/openpaas/linagora.esn.calendar
  script:
    - perl -i -pe's/"host":"localhost:8080"/"schemes":["https"],"host":"demo.open-paas.org"/' ./doc/swagger/calendar-swagger.json
    - cp ./doc/swagger/calendar-swagger.json /var/www/html

deploy_dev:
  stage: deploy
  except:
    - triggers
  tags:
    - dev.open-paas.org
    - deployment
  environment:
    name: dev
    url: https://dev.open-paas.org
  only:
    - master@linagora/lgs/openpaas/linagora.esn.calendar
  script:
    - cd /srv/${CI_PROJECT_NAME}
    - git fetch --all
    - git checkout ${CI_COMMIT_SHA}
    - npm install --ignore-scripts --production
    - npm update --production
    - npm prune
    - bower install --production
    - bower prune
    - git checkout -- .
    - sudo /etc/init.d/rse.dev restart

release:
  stage: release
  only:
    - triggers
  script:
    - if [ -z "${VERSION}" ]; then exit 0; fi
    - ./node_modules/.bin/grunt release:${VERSION}
